version: '3.3'
services:
  jenkins-agent:
    build:
      context: ./jenkins-agent
      args:
        - SSH_AGENT_VERSION=${JENKINS_SSH_AGENT_VERSION}
    container_name: jenkins-agent
    ports:
      - "${JENKINS_SSH_AGENT_PORT}:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
# Uncomment these lines if you want to connect to an external docker network
#networks:
#  default:
#    name: jenkins
#    external: true
